import Order from "../bottom/Order";

export const CUSTOMER_URL =
  'https://crm.codeverse.co/cedge/get-customer-url/crm/';

export const API = {
  LOGIN: 'hexaportal/oauth/token',
  LOCATION: 'hexaportal/api/style/cedge/getLocationInventory',
  ALL_PRODUCTS_DATA: 'hexaportal/api/style/findallstyles',
  ALL_CATEGORIES_DATA: 'hexaportal/api/category/getcategoriesByCompanyId',
  STYLE_QUNTITY_DATA: 'hexaportal/api/style',
  STYLE_QUNTITY_DATA_NEW:'hexaportal/api/style/getStyleWitUnOrderedQty',
  ADD_ORDER_DATA: 'hexaportal/api/ordermgmt/adddistributororder',
  ADD_CUSTOMER_LIST: 'hexaportal/api/customers',
  GET_ALL_ORDER: 'hexaportal/api/ordermgmt/findAllDisOrders',
  GET_CUSTOMER_LOCATION: 'hexaportal/api/location/getLocationsAccCustomer',
  ADD_CUSTOMER_DETAILS: 'hexaportal/api/customers/addcustomer',
  ADD_DISTRIBUTOR_DETAILS: 'hexaportal/api/distributors/addDistributor',
  ADD_CUSTOMER_LOCATION: 'hexaportal/api/location/addlocation',
  ADD_USERS: 'hexaportal/api/users',
  ADD_USERSDECS: 'hexaportal/api/users/getusersDesc',
  STATUS_OPTION:'hexaportal/api/master/getStatusForcompId',
  ADD_PRODUCT_INVENTORY: 'hexaportal/api/style/cedge/getMainInventory',
  ADD_LOCATION_INVENTORY: 'hexaportal/api/style/cedge/getLocationInventory',
  GET_ORDER_PACKING: 'hexaportal/api/ordermgmt/getOrderPacking',
  ADD_GENERATED_PDF:  'hexaportal/api/ordermgmt/generatePdf',
  ADD_GENERATED_PDF_INVOICEFORMAT:  'hexaportal/api/ordermgmt/prepareInvoicePDF',
  GET_DISTRIBUTOR_GRN:'hexaportal/api/ordermgmt/findAllGrnOrders',
  GET_DISTRIBUTOR_ORDER: 'hexaportal/api/ordermgmt/disOrdersById',
  ADD_GRN_ORDER: 'hexaportal/api/ordermgmt/addgrnorder',
  GET_COMPANY:'hexaportal/api/company',
  GET_ALL_TASK:'hexaportal/api/master/getAllTasksByDesc',
  GET_ALL_CALL:'hexaportal/api/master/getAllCallsByDesc',
  ADD_NEW_TASK:'hexaportal/api/master/addTask',
  GET_TASK_BY_ID:'hexaportal/api/master/getTask',
  ADD_NEW_CALL:'hexaportal/api/master/addCall',
  GET_CALL_BY_ID:'hexaportal/api/master/getCall',
  ADD_UPDATE_TASK:'hexaportal/api/master/addTask',
  GET_DISTRIBUTORS_DETAILS:'hexaportal/api/distributors',
  GET_USER_IN_ACTIVE:'hexaportal/api/users/updateUserInActive',
  GENERATE_CATE_LOG:'hexaportal/api/ordermgmt/generateCatelog',
  VALIDATIONDISTRIBUTOR:"hexaportal/api/distributors/isValiddistributor",
  VALIDATIONCUSTOMER:"hexaportal/api/customers/isValidCustomer",
  VALIDATIONLOACTION:"hexaportal/api/location/isValid",
  ALL_PRODUCTS_DATA_NEW: 'hexaportal/api/style/getAll',
  GET_TASKS_ACC_USER:'hexaportal/api/master/getTasksAccUser',
  GET_TASKS_ACC_USER_LAZY:'hexaportal/api/master/getTasksAccUserLazy',
  GET_Fields_List:'hexaportal/api/master/getField',
  GET_CATEGORY_LIST:'hexaportal/api/category/getAllCategories/',
  GET_COLOR_LIST:'hexaportal/api/color/getByCompanyId/',
  GET_CUSTOMERLEVEL_LIST:'hexaportal/api/customerlevel/types',
  GET_TYPES_LIST:'hexaportal/api/type/getByCompanyId/',
  GET_ALL_INDUSTRYTYPES_LIST:'hexaportal/api/master/getAllIndustryTypes/',
  GET_SEASONGROUP_LIST:'hexaportal/api/sizegroup/getBycompanyId/',
  GET_PROCESSWORKFLOW_LIST:'hexaportal/api/master/getAllProcessConfig',
  GET_LOCATION_C0_LIST:'hexaportal/api/style/cedge/getCompanyLocations',
  // GET_LOCATION_C1_LIST:'hexaportal/api/location/withNames/',
  GET_LOCATION_C1_LIST:'hexaportal/api/location/getCompanyLocations/',
  GET_SCALES:'hexaportal/api/scale/',
  VALIDATE_CATEGORY:'hexaportal/api/category/isValidCategory/',
  ADD_CATEGORY:'hexaportal/api/category/addcategory',
  VALIDATE_COLOR:'hexaportal/api/color/isValid/',
  ADD_COLOR:'hexaportal/api/color/addcolor',
  VALIDATE_TYPE:'hexaportal/api/type/isValid/',
  ADD_TYPE:'hexaportal/api/type/addtype',
  VALIDATE_SEASON_GROUP:'hexaportal/api/sizegroup/isValid/',
  ADD_SEASON_GROUP:'hexaportal/api/sizegroup/addsize',
  VALIDATE_SCALE:'hexaportal/api/size/isValid/',
  ADD_SCALE:'hexaportal/api/size/addsizes',
  ALL_SIZES_IN_SCALE:'hexaportal/api/size/getByCompanyId',
  GET_STYLE_BY_ID:'hexaportal/api/style/',
  GET_STYLE_LIST:'hexaportal/api/style/getAll/',
  ADD_NEW_SCALE:'hexaportal/api/scale/addScale',
  ADD_NEW_STYLE:'hexaportal/api/style/addstyle',
  EDIT_NEW_STYLE:'hexaportal/api/style/editstyle',
  LOGINAUDIT:'hexaportal/api/master/addLoginoutAudit',
  GET_ALL_STATUS:'hexaportal/api/ordermgmt/getAllStatus',
  UPDATE_DIS_ORDERl:'hexaportal/api/ordermgmt/updateDisOrder',
  UPDATE_DIS_ORDER:'hexaportal/api/ordermgmt/updateDistributorOrder',
  ADD_LOCATION_IMAGES:'hexaportal/api/master/addLocation',
  GET_Location:'hexaportal/api/master/getLocation',
  GET_NOTIFICATION_LIST:'hexaportal/api/master/getMessages',
  UPDATE_READ_MSG:'hexaportal/api/master/updateRead',
  GET_KAPTURE:'hexaportal/api/master/getAllMasters',
  VALIDATE_KAPTURE:'hexaportal/api/master/isValidClosures',
  ADD_KAPTURE:'hexaportal/api/master/saveMaster',
  GET_DISTRIBUTOR_INVENTORY:'hexaportal/api/ordermgmt/getAllDisInventoryLazy',
  GET_DISTRIBUTOR_INVENTORY_SEARCH:'hexaportal/api/filter/getdisInventoryLazyLoad',
  GET_CLEARALL_MESSAGE:'hexaportal/api/master/clearAllNotifications',
  ADD_ALL_INVENTORY_LAZY:'hexaportal/api/style/cedge/getAllInventoryLazy',
  GET_ALL_INVENTORY_SEARCH:'hexaportal/api/filter/getStyleInventoryForsearchLazyLoad',
  ADD_LOCATION_INVENTORY_LAZY:'hexaportal/api/style/cedge/getLocationInventoryLazy',
  GET_ALL_LOCATION_INVENTORY_SEARCH:'hexaportal/api/filter/getLocationInventoryForsearchLazyLoad',
  GET_ALL_ORDER_LAZY: 'hexaportal/api/ordermgmt/getAllOrdersForLazyLoad',
  GET_ALL_ORDER_SEARCH:'hexaportal/api/filter/getAllOrdersSearchForLazyLoad',
  GET_ALL_STYLE_LAZY:'hexaportal/api/style/getAllStyleLazy',
  GET_ALL_STYLE_LAZY_SEARCH:'hexaportal/api/filter/getStyleProductDataForLazyLoad',
  PUNCH_IN_PUNCH_OUT:'hexaportal/api/master/updateAttendanceSwape',
  GET_PUNCH_IN_PUNCH_OUT:'hexaportal/api/master/getAttendanceSwapes',
  CHECK_IN_CHECK_OUT:'hexaportal/api/master/updateTaskPunchInOut',
  GET_PACKAGES:'hexaportal/api/package/getMobPackegeLazy',
  GET_PACKAGES_SERACH:'hexaportal/api/filter/getPackegeDataForMobLazyLoad',
  GET_ALL_PACKAGES_DETAILS:'hexaportal/api/package/getPackageMobile',
  GET_PACKAGES_MODEL:'hexaportal/api/package',
  GET_ALL_TASK_LAZY:'hexaportal/api/master/getAllTasksFromTo',
  GET_ALL_CALL_LAZY:'hexaportal/api/master/getAllCallsFromTo',
  GET_ALL_TASK__SEARCH:'hexaportal/api/master/getTasksSearchFromTo',
  GET_ALL_CALL_SEARCH:'hexaportal/api/master/getCallsSearchFromTo',
  SEARCH_DISTRIBUTOR_GRN:'hexaportal/api/filter/getDistributorGRNBasedOnTypeServices',
  SEARCH_ALL_PRODUCTS:'hexaportal/api/style/searchAllStylesMobile',
  SEARCH_ALL_CATEGORIES_LL:'hexaportal/api/filter/getCategoryBasedOnTypeServicesMob',
  ALL_CATEGORIES_LL_LIST: 'hexaportal/api/category/getAllCategoryLazyLoadForMob',
  GET_DISTRIBUTOR_GRN_LL:'hexaportal/api/ordermgmt/getAllDistributorGRNLazyLoad',
  GET_ALL_PRODUCT_PUBLISH_LAZY:'hexaportal/api/style/getAllStyleLazyPublish',
  SEARCH_ALL_PRODUCT_PUBLISH:'hexaportal/api/filter/getStyleProductDataForLazyLoad',
  GET_ALL_IMAGES:'hexaportal/api/style/getImgBasedOnId',
  GET_ALL_IMAGES_PACKAGE:'hexaportal/api/package',
  REQUEST_OTP:'hexaportal/api/users/requestOtp',
  CONFIRM_OTP:'hexaportal/api/users/confirmOtp',
  RESET_PASSWORD:'hexaportal/api/users/resetPassword',
  ADD_NEW_LOCATION:'hexaportal/api/location/updateUserNewLocationForMobile',
  GET_STYLE_ITEMS:'hexaportal/api/style/getStylesWithSizesByBarcode',
  GET_PACKAGES_ITEMS:'hexaportal/api/package/getPackageDtlsByBarcode',
  GET_COSTING:'hexaportal/api/costing/getAllCostForLazyLoad',
  SEARCH_COSTING:'hexaportal/api/costing/getCostBasedOnTypeServices',
  ADD_COSTING:'hexaportal/api/costing/addCosting',
  GET_ALL_THE_ROLE_MENU:'hexaportal/api/rolemenu/rolewisemobilemenus',
  GET_ALL_THE_MENUS_FOR_MOBILE:'hexaportal/api/menu/allmobilemenus',
  GET_ALL_ADDED_COSTING_DETAILSL:'hexaportal/api/costing',
  CHECKAVALABILITY:'hexaportal/api/style/checkStyleAvailQty',
  GET_STATE:'hexaportal/api/master/getAllStates',
  GET_SELECT_STYLE:'hexaportal/api/style/getStyles',
  GET_STYLE_COLOR:'hexaportal/api/style/getAllStylesAccComp',
  GET_SKU:'hexaportal/api/style/getAllSkusAccComp',
  GET_ALL_SKU_SEARCH:'hexaportal/api/style/getStyleFilterData',
  GET_SIZES_BY_SCALE_ID:'hexaportal/api/scale',
  VALIDATE_NAME_COLOR:'hexaportal/api/style/isValidStyle',
  ADD_COPY_STYLE:'hexaportal/api/style/addCopyStyle',
  GET_UOM:'hexaportal/api/uom/getByCompanyId',
  ADD_UOM:'hexaportal/api/uom/addUOM',
  VALIDATE_UOM:'hexaportal/api/uom/isValidUOM/',
  STYLE_BASED_ON_SEARCH:'hexaportal/api/style/getStyleBasedOnSearchType',
  GET_GST_SLOT:'hexaportal/api/Gst',
  ADD_SLOT:'hexaportal/api/Gst/addGst',
  VALIDATE_SLOT:'hexaportal/api/Gst/isValidGst/',
  PICK_LIST_PAGE:'hexaportal/api/ordermgmt/getAllOrdersForLazyLoad',
  PICK_LIST_PAGE_SEARCH:'hexaportal/api/filter/getAllOrdersSearchForLazyLoad',
  PICK_LIST_PDF:'hexaportal/api/ordermgmt/generatePackListPdf',
  PICK_LIST_EDIT:'hexaportal/api/ordermgmt/getPackList',
  GENARATE_PICK_LIST:'hexaportal/api/ordermgmt/updatePackList',
  MASTER_LOCATION:'hexaportal/api/location/getAlllocationLazy',
  MASTER_LOCATION_SEARCH:'hexaportal/api/filter/getlocationDataForLazyLoad',
  MASTER_LOCATION_EDIT:'hexaportal/api/location',
  MASTER_EDIT_LOCATION:'hexaportal/api/location/editlocation',
  MASTER_EDIT_LOCATION_VALIDATE:'hexaportal/api/location/isValid',
  CLOSE_ORDER_PICKLIST:'hexaportal/api/ordermgmt/closePicklistOrder',
  GET_BARCODE:'hexaportal/api/style/getBarcode',
  GET_ALL_ORDER_RETURNS_LAZY: 'hexaportal/api/ordermgmt/getAllOrderReturnLazyLoad',
  GET_ALL_ORDER_RETURNS_LAZY_SEARCH:'hexaportal/api/filter/getOrderReturnBasedOnTypeServices',
  GET_ORDER_RETURNSEDIT_BY_ID:'hexaportal/api/ordermgmt/disOrdersById',
  GET_RETURN_REASON:'hexaportal/api/returns/getByCompanyId',
  GET_RETURN_REASON_VALIDATE:'hexaportal/api/returns/isValid/',
  ADD_RETURN_REASON:'hexaportal/api/returns/addreturns',
  GET_ORDER_RETURN: 'hexaportal/api/ordermgmt/getOrderPacking',
  ADD_ORDER_RETURN: 'hexaportal/api/ordermgmt/addRetOrder',
  GET_PRICE_LIST: 'hexaportal/api/priceList/getByCompanyId',
  ADD_PRICE_LIST: 'hexaportal/api/priceList/addPriceList',
  VALIDATE_PRICE_LIST: 'hexaportal/api/priceList/isValidPriceList/',
  GET_STYLES_ON_DISTRIBUTOR_CHANGED:'hexaportal/api/style/getStylesOnDistributorChanged',
  ORDER_RETURNS_MODEL:'hexaportal/api/ordermgmt/getDisOrderReturns',
  PDF_DOWNLOAD_FOR_ORDER_RETURNS_MODEL:'hexaportal/api/ordermgmt/prepareOrderReturnPdf',
  PDF_DOWNLOAD_ORDER_RETURNS:'hexaportal/api/ordermgmt/generateSalesReturnPDF',
  GET_CREDI_TNOTES:'hexaportal/api/creditNote/getCreditNotesFromTo',
  GET_CREDI_TNOTES_SEARCH:'hexaportal/api/creditNote/getCreditNotesSearchFromTo',
  GET_CREDI_TNOTES_EDIT:'hexaportal/api/creditNote',
  CREDI_TNOTES_PDF:'hexaportal/api/creditNote/generatePdf'
};

export const USER_ID = 'adminClientId';
export const USER_PASSWORD = 'erpPortalAdmin';




