export const PRODUCT_DETAILS=[
    {
        id:1,
        price:"10000",
        tags:"null",
        disription:"Watch out this space for more details",
        name:"TTH Membership",
        image:require('../../assets/vip.png'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),
    },
    {
        id:2,
        price:"10000",
        tags:"null",
        disription:"Watch out this space for more details",
        name:"Starter Kit",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),

    },
    {
        id:3,
        price:"10000",
        tags:"null",
        disription:"Watch out this space for more details",
        name:"Classic Hoodies",
        image:require('../../assets/img2.jpg'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),

    },
    {
        id:4,
        price:"20000",
        tags:"null",
        disription:"Watch out this space for more details",
        name:"2 IN 1 Zipper",
        image:require('../../assets/img3.jpg'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),

    },
    {
        id:5,
        price:"10000",
        tags:"null",
        disription:"Watch out this space for more details",
        name:"Crewneks",
        image:require('../../assets/img2.jpg'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),

    },
    {
        id:6,
        price:"10000",
        tags:"null",
        disription:"Watch out this space for more details",
        name:"Polos",
        image:require('../../assets/img2.jpg'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),

    },
];
